/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './async-local-storage_module';
import * as import2 from './async-local-storage';
class AsyncLocalStorageModuleInjector extends import0.ɵNgModuleInjector<import1.AsyncLocalStorageModule> {
  _AsyncLocalStorageModule_0:import1.AsyncLocalStorageModule;
  __AsyncLocalStorage_1:any;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _AsyncLocalStorage_1():any {
    if ((this.__AsyncLocalStorage_1 == null)) { (this.__AsyncLocalStorage_1 = import1.asyncLocalStorageFactory()); }
    return this.__AsyncLocalStorage_1;
  }
  createInternal():import1.AsyncLocalStorageModule {
    this._AsyncLocalStorageModule_0 = new import1.AsyncLocalStorageModule();
    return this._AsyncLocalStorageModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.AsyncLocalStorageModule)) { return this._AsyncLocalStorageModule_0; }
    if ((token === import2.AsyncLocalStorage)) { return this._AsyncLocalStorage_1; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const AsyncLocalStorageModuleNgFactory:import0.NgModuleFactory<import1.AsyncLocalStorageModule> = new import0.NgModuleFactory<any>(AsyncLocalStorageModuleInjector,import1.AsyncLocalStorageModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2N5cmlsbGUvV2ViL2dpdGh1Yi9hbmd1bGFyLWFzeW5jLWxvY2FsLXN0b3JhZ2Uvc3JjL2FzeW5jLWxvY2FsLXN0b3JhZ2VfbW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2N5cmlsbGUvV2ViL2dpdGh1Yi9hbmd1bGFyLWFzeW5jLWxvY2FsLXN0b3JhZ2Uvc3JjL2FzeW5jLWxvY2FsLXN0b3JhZ2VfbW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
