/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './async-local-storage_module';
import * as import2 from '@angular/core/src/di/injector';
import * as import3 from './async-local-storage';
class AsyncLocalStorageModuleInjector extends import0.NgModuleInjector<import1.AsyncLocalStorageModule> {
  _AsyncLocalStorageModule_0:import1.AsyncLocalStorageModule;
  __AsyncLocalStorage_1:any;
  constructor(parent:import2.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _AsyncLocalStorage_1():any {
    if ((this.__AsyncLocalStorage_1 == (null as any))) { (this.__AsyncLocalStorage_1 = import1.asyncLocalStorageFactory()); }
    return this.__AsyncLocalStorage_1;
  }
  createInternal():import1.AsyncLocalStorageModule {
    this._AsyncLocalStorageModule_0 = new import1.AsyncLocalStorageModule();
    return this._AsyncLocalStorageModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.AsyncLocalStorageModule)) { return this._AsyncLocalStorageModule_0; }
    if ((token === import3.AsyncLocalStorage)) { return this._AsyncLocalStorage_1; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const AsyncLocalStorageModuleNgFactory:import0.NgModuleFactory<import1.AsyncLocalStorageModule> = new import0.NgModuleFactory(AsyncLocalStorageModuleInjector,import1.AsyncLocalStorageModule);